#!/bin/bash

#SBATCH -J GC_telo

#SBATCH --mail-type=END,FAIL

#SBATCH --cpus-per-task=1
#SBATCH --mem=8G
#SBATCH --time=2:00:00

export PATH="${CONDA_BIN_DIR}:${PATH}"
source activate jATG_env


mkdir -p ${OUT_DIR}/jATG/${SPECIES_NAME}/${ASSEMBLY_ID}/3.gc_telo/plots
cd ${OUT_DIR}/jATG/${SPECIES_NAME}/${ASSEMBLY_ID}/3.gc_telo


if [[ "${ASSEMBLY##*.}" == "gz" ]]
then
    INTER=$(basename ${ASSEMBLY} .gz)
    export ASSEMBLY_NAME=$(basename $INTER .${INTER##*.})
    if [[ -e ${TMPDIR}/${ASSEMBLY_NAME}.fa ]]
    then
        echo "decompressed file exist, creating the link..."
        ln -s "${TMPDIR}/${ASSEMBLY_NAME}.fa" "${ASSEMBLY_NAME}.fa"
    else
        echo "decompressing the file..."
        gunzip -c ${ASSEMBLY} > "${TMPDIR}/${ASSEMBLY_NAME}.fa"
        ln -s "${TMPDIR}/${ASSEMBLY_NAME}.fa" "${ASSEMBLY_NAME}.fa"
    fi
elif  [[ "${ASSEMBLY##*.}" == "fa" ]] || [[ "${ASSEMBLY##*.}" == "fasta" ]] || [[ "${ASSEMBLY##*.}" == "fna" ]]
then
    echo "crating the link..."
    export ASSEMBLY_NAME=$(basename $ASSEMBLY .${ASSEMBLY##*.})
    ln -s ${ASSEMBLY} "${ASSEMBLY_NAME}.fa"
else
    echo "Invalid reference extension name!"
fi


# GC
cat ${ASSEMBLY_NAME}.fa | seqkit fx2tab -n -l -g > ${ASSEMBLY_NAME}_GC.tab
cat ${ASSEMBLY_NAME}.fa | seqkit sliding -s ${WINDOW_GC} -W ${WINDOW_GC} -g | seqkit fx2tab -n -g > ${ASSEMBLY_NAME}_gc_window${WINDOW_GC}.tab


# Telo
tidk find --log -w ${WINDOW_TELO} -c ${CLADE} -d ${OUT_DIR}/jATG/${SPECIES_NAME}/${ASSEMBLY_ID}/3.gc_telo -o ${ASSEMBLY_NAME} ${ASSEMBLY_NAME}.fa


# Gaps
seqtk cutN -n 1 -g ${ASSEMBLY_NAME}.fa > ${ASSEMBLY_NAME}_gaps.bed
python ${INSTALLATION_DIR}/3.gc_telo/scripts/completeGapbED.py -b ${ASSEMBLY_NAME}_gaps.bed -g ${GENOME_TABLE} -o ${ASSEMBLY_NAME}_resolved.bed


# Plots
Rscript ${INSTALLATION_DIR}/3.gc_telo/scripts/plotGC_TELO.R ${GENOME_TABLE} ${MINSIZE} ${ASSEMBLY_NAME}_gc_window${WINDOW_GC}.tab ${ASSEMBLY_NAME}_telomeric_repeat_windows.tsv ${ASSEMBLY_NAME}_resolved.bed ${OUT_DIR}/jATG/${SPECIES_NAME}/${ASSEMBLY_ID}/3.gc_telo/plots


#Rscript scripts/plotGC_karyoploteR.R ${GENOME_FILE} ${MINSIZE} ${OUT_DIR}/${OUT_PREFIX}_gc_window${WINDOW}.tab ${OUT_DIR}/${OUT_PREFIX}_GC.tab ${OUT_DIR}/plots

