# variables for the repeats annotation and masking pipeline:
export INSTALLATION_DIR="/home/ddepanis/jATG" #where the cloned repo folder is
export OUT_DIR="/scratch/ddepanis/results" #where the jATG folder will be created

# conda-specific variables
export CONDA_BIN_DIR="/scratch/ddepanis/Software/anaconda3/bin"

# singularity-specific variables
export BIND_DIR="/scratch/ddepanis/"

# slurm-specific variables
export USER_MAIL='ddepanis@zedat.fu-berlin.de'
export PARTITION='begendiv,main'
export QUEUE="standard"
export LOAD_SINGULARITY='module load singularity' # comment this line if singularity is in path
