#!/bin/bash

#SBATCH -J SexChr

#SBATCH --mail-type=END,FAIL

#SBATCH --cpus-per-task=6
#SBATCH --mem=18G
#SBATCH --time=2-00:00:00

export PATH="${CONDA_BIN_DIR}:${PATH}"
source activate STATS_env


cd ${OUT_DIR}/jATG/${SPECIES_NAME}/${ASSEMBLY_ID}/1.stats



python ${INSTALLATION_DIR}/1.stats/scripts/search_sex_scaffolds.py ${USER_MAIL} ${REF_SPECIES_NAME}


miniprot -t8 ${ASSEMBLY} ${REF_SPECIES_NAME}_sexChrSeqs.faa > sexChr.paf


