#!/bin/bash

#SBATCH -J Stats

#SBATCH --mail-type=END,FAIL

#SBATCH --cpus-per-task=1
#SBATCH --mem=8G
#SBATCH --time=2:00:00

export PATH="${CONDA_BIN_DIR}:${PATH}"
source activate jATG_env

${SINGULARITY_LOAD}

LC_ALL=C


mkdir -p ${TMPDIR}
cd ${OUT_DIR}/jATG/${SPECIES_NAME}/${ASSEMBLY_ID}/1.stats


if [[ "${ASSEMBLY##*.}" == "gz" ]]
then
    INTER=$(basename ${ASSEMBLY} .gz)
    export ASSEMBLY_NAME=$(basename $INTER .${INTER##*.})
    if [[ -e ${TMPDIR}/${ASSEMBLY_NAME}.fa ]]
    then
        echo "decompressed file exist, creating the link..."
        ln -s "${TMPDIR}/${ASSEMBLY_NAME}.fa" "${ASSEMBLY_NAME}.fa"
    else
        echo "decompressing the file..."
        gunzip -c ${ASSEMBLY} > "${TMPDIR}/${ASSEMBLY_NAME}.fa"
        ln -s "${TMPDIR}/${ASSEMBLY_NAME}.fa" "${ASSEMBLY_NAME}.fa"
    fi
elif  [[ "${ASSEMBLY##*.}" == "fa" ]] || [[ "${ASSEMBLY##*.}" == "fasta" ]] || [[ "${ASSEMBLY##*.}" == "fna" ]]
then
    echo "crating the link..."
    export ASSEMBLY_NAME=$(basename $ASSEMBLY .${ASSEMBLY##*.})
    ln -s ${ASSEMBLY} "${ASSEMBLY_NAME}.fa"
else
    echo "Invalid reference extension name!"
fi



assembly-stats "${ASSEMBLY_NAME}.fa" > assembly_stats.tmp
python ${INSTALLATION_DIR}/1.stats/scripts/table_from_stats.py assembly_stats.tmp > temp_${ASSEMBLY_NAME}_shortStats.tsv
cat temp_${ASSEMBLY_NAME}_shortStats.tsv | csvtk tab2csv | csvtk csv2md > ${ASSEMBLY_NAME}_shortStats.md
rm assembly_stats.tmp
rm temp_${ASSEMBLY_NAME}_shortStats.tsv

countgc.sh "${ASSEMBLY_NAME}.fa" format=1 > temp
cut -f1 temp > full_fasta_header
awk '{print $1}' temp > col1_temp
awk -F "\t" '{print $2}' temp > col2_temp
awk -F "\t" '{print $7}' temp > col4_temp
awk -F "\t"  '{print $8}' temp > col3_temp
paste col1_temp col2_temp col3_temp col4_temp | awk 'NF' | sort -k 2 -n -r | awk '{print NR"\t"$s}' > number_lengths_GC_Ns
rm *temp

awk '$3 > 5000000 { print $2 }' number_lengths_GC_Ns > main_scaffolds


singularity exec -B ${BIND_DIR}:${BIND_DIR} ${INSTALLATION_DIR}/containers/gatk_latest.sif samtools \
faidx "${ASSEMBLY_NAME}.fa"
