#!/bin/bash

#SBATCH -J Darw.plot

#SBATCH --cpus-per-task=2
#SBATCH --mem=8G
#SBATCH --time=06:00:00

export PATH="${CONDA_BIN_DIR}:${PATH}"
source activate CALLING_env


cd ${OUT_DIR}/jATG/${SPECIES_NAME}/${ASSEMBLY_ID}/${SAMPLE_NAME}/5.het_roh

Rscript ${INSTALLATION_DIR}/5.het_roh/scripts/Darwindow_plots.R \
${INSTALLATION_DIR}/5.het_roh/scripts/VCF_darwindow.plotinR.txt \
${OUT_DIR}/jATG/${SPECIES_NAME}/${ASSEMBLY_ID}/${SAMPLE_NAME}/5.het_roh \
100000.${SAMPLE_NAME}.txt
