#!/bin/bash

#SBATCH -J Cons

#SBATCH --cpus-per-task=1
#SBATCH --mem=1G
#SBATCH --time=12:00:00

export PATH="${CONDA_BIN_DIR}:${PATH}"
source activate PSMC_env

cd ${OUT_DIR}/jATG/${SPECIES_NAME}/${ASSEMBLY_ID}/${SAMPLE_NAME}/6.psmc


if [ -z "${SEX_CHROM_NAME}" ]
then
	cp ${MAIN_CHROM} scaffolds_ok
else
	sed "/${SEX_CHROM_NAME}/d" ${MAIN_CHROM} > scaffolds_ok
fi

bcftools view -r $(paste -s -d, scaffolds_ok) \
${OUT_DIR}/jATG/${SPECIES_NAME}/${ASSEMBLY_ID}/${SAMPLE_NAME}/4.calling/2_VCFs/filt/${SAMPLE_NAME}.PASS.masked_filtered.vcf.gz | bgzip > scaffolds_ok.vcf.gz

bcftools index scaffolds_ok.vcf.gz

cat ${ASSEMBLY_HM} | bcftools consensus -I scaffolds_ok.vcf.gz > ${SAMPLE_NAME}_consensus.fasta
#-I: It uses the ambiguity codes. For example "nucleotide" Y means that position is heterozygote for C and T nucleotides. If you have a Y in your sliding window, PSMC calls that window to have heterozygosity. SNPs are converted into these IUPAC codes to represent diploid information in a haploid-like single sequence in the prior step.


