#!/bin/bash

#SBATCH -J Conv

#SBATCH --cpus-per-task=1
#SBATCH --mem=1G
#SBATCH --time=12:00:00

export PATH="${CONDA_BIN_DIR}:${PATH}"
source activate PSMC_env


cd ${OUT_DIR}/jATG/${SPECIES_NAME}/${ASSEMBLY_ID}/${SAMPLE_NAME}/6.psmc

fq2psmcfa ${SAMPLE_NAME}_consensus.fasta > ${SAMPLE_NAME}.psmcfa

#Split sequences to perform bootstrapping
splitfa ${SAMPLE_NAME}.psmcfa > ${SAMPLE_NAME}.psmcfa.split.psmcfa

