#!/bin/bash

#SBATCH -J Plot

#SBATCH --cpus-per-task=1
#SBATCH --mem=2G
#SBATCH --time=2-00:00:00

export PATH="${CONDA_BIN_DIR}:${PATH}"
source activate PSMC_env


cd ${OUT_DIR}/jATG/${SPECIES_NAME}/${ASSEMBLY_ID}/${SAMPLE_NAME}/6.psmc

mkdir plots

psmc_plot.pl -u ${MUTATION} -g ${GENERATION} -R -T ${SAMPLE_NAME} -p "plots/${SAMPLE_NAME}_plot" "${SAMPLE_NAME}.combined.psmc"

# -u: per-generation mutation rate  
# -g: generation time in years
