#!/bin/bash

#SBATCH -J Plot

#SBATCH --cpus-per-task=8
#SBATCH --mem=48G
#SBATCH --time=2-00:00:00

export PATH="${CONDA_BIN_DIR}:${PATH}"
source activate PSMC_env


cd ${OUT_DIR}/jATG/${SPECIES_NAME}/${ASSEMBLY_ID}/${SAMPLE_NAME}/6.psmc


psmc_plot.pl -u ${MUTATION} -g ${GENERATON} -R -T ${SAMPLE_NAME} -p ${SAMPLE_NAME}_plot ${SAMPLE_NAME}.combined.psmc

# -u: per-generation mutation rate  
# -g: generation time in years
