#!/bin/bash

#SBATCH -J GATK

#SBATCH --cpus-per-task=4
#SBATCH --mem=48G
#SBATCH --time=36:00:00

export PATH="${CONDA_BIN_DIR}:${PATH}"
source activate jATG_env

${SINGULARITY_LOAD}

cd ${OUT_DIR}/jATG/${SPECIES_NAME}/${ASSEMBLY_ID}/${SAMPLE_NAME}/4.calling/2_VCFs


# get ASSEMBLY_NAME variable and file in deepvariant folder (because it complains otherwise)
if [[ "${ASSEMBLY##*.}" == "gz" ]]
then
	INTER=$(basename ${ASSEMBLY} .gz)
        ASSEMBLY_NAME=$(basename $INTER .${INTER##*.})
#        gunzip -c ${ASSEMBLY} > "${ASSEMBLY_NAME}.fa"
elif  [[ "${ASSEMBLY##*.}" == "fa" ]] || [[ "${ASSEMBLY##*.}" == "fasta" ]] || [[ "${ASSEMBLY##*.}" == "fna" ]]
then
        ASSEMBLY_NAME=$(basename $ASSEMBLY .${ASSEMBLY##*.})
#        cp ${ASSEMBLY} "${ASSEMBLY_NAME}.fa"
else
        echo "Invalid reference extension name!"
fi


#cp "${OUT_DIR}/jATG/${SPECIES_NAME}/${ASSEMBLY_ID}/${SAMPLE_NAME}/4.calling/0_idx/${ASSEMBLY_NAME}.fa.fai" .


INTERVAL=$(ls ${OUT_DIR}/jATG/${SPECIES_NAME}/${ASSEMBLY_ID}/${SAMPLE_NAME}/4.calling/0_idx/interval*.list 2>/dev/null | head -n ${SLURM_ARRAY_TASK_ID} | tail -n 1)
INTERVAL_NAME=$(basename $INTERVAL .list)

LC_ALL=C

singularity exec -B ${BIND_DIR}:${BIND_DIR} ${INSTALLATION_DIR}/containers/gatk_latest.sif gatk \
--java-options "-Xmx${SLURM_MEM_PER_NODE}M" HaplotypeCaller \
--reference ${OUT_DIR}/jATG/${SPECIES_NAME}/${ASSEMBLY_ID}/${SAMPLE_NAME}/4.calling/0_idx/${ASSEMBLY_NAME}.fa \
--input ${OUT_DIR}/jATG/${SPECIES_NAME}/${ASSEMBLY_ID}/${SAMPLE_NAME}/4.calling/1_BAMs/${SAMPLE_NAME}.merged.bam \
--intervals ${INTERVAL} \
--output ${SAMPLE_NAME}.HapCal.${INTERVAL_NAME}.vcf.gz \
--output-mode EMIT_ALL_CONFIDENT_SITES \
-ERC BP_RESOLUTION \
--tmp-dir ${TMPDIR} \
--native-pair-hmm-threads ${SLURM_CPUS_PER_TASK}


singularity exec -B ${BIND_DIR}:${BIND_DIR} ${INSTALLATION_DIR}/containers/gatk_latest.sif gatk \
--java-options "-Xmx${SLURM_MEM_PER_NODE}M" GenotypeGVCFs \
--reference ${OUT_DIR}/jATG/${SPECIES_NAME}/${ASSEMBLY_ID}/${SAMPLE_NAME}/4.calling/0_idx/${ASSEMBLY_NAME}.fa \
--variant ${SAMPLE_NAME}.HapCal.${INTERVAL_NAME}.vcf.gz \
--output ${SAMPLE_NAME}.Genot.${INTERVAL_NAME}.vcf.gz \
--include-non-variant-sites \
--standard-min-confidence-threshold-for-calling 0 \
--tmp-dir ${TMPDIR}

