#!/bin/bash

#SBATCH -J Deepvariant

#SBATCH --cpus-per-task=18
#SBATCH --mem=64G
#SBATCH --time=36:00:00

export PATH="${CONDA_BIN_DIR}:${PATH}"
source activate CALLING_env

${SINGULARITY_LOAD}

cd ${OUT_DIR}/jATG/${SPECIES_NAME}/${ASSEMBLY_ID}/${SAMPLE_NAME}/4.calling/2_VCFs


# get ASSEMBLY_NAME variable and file in deepvariant folder (because it complains otherwise)
if [[ "${ASSEMBLY##*.}" == "gz" ]]
then
	INTER=$(basename ${ASSEMBLY} .gz)
        ASSEMBLY_NAME=$(basename $INTER .${INTER##*.})
        gunzip -c ${ASSEMBLY} > "${ASSEMBLY_NAME}.fa"
elif  [[ "${ASSEMBLY##*.}" == "fa" ]] || [[ "${ASSEMBLY##*.}" == "fasta" ]] || [[ "${ASSEMBLY##*.}" == "fna" ]]
then
        ASSEMBLY_NAME=$(basename $ASSEMBLY .${ASSEMBLY##*.})
        cp ${ASSEMBLY} "${ASSEMBLY_NAME}.fa"
else
        echo "Invalid reference extension name!"
fi


cp "${OUT_DIR}/jATG/${SPECIES_NAME}/${ASSEMBLY_ID}/${SAMPLE_NAME}/4.calling/0_idx/${ASSEMBLY_NAME}.fa.fai" .


# 
if [[ "${READ_TYPE}" == "illuminaPE" ]]
then

	# get READ/SAMPLE variables
#	if [ -z "${MULTI_RUN}" ]
#	then
#		READ=$(ls ${TRIM_DIR}/*_R1.trimmed.fq.gz | tail -n 1)
#		READ_NAME=$(basename ${READ} _R1.trimmed.fq.gz)
#		SAMPLE_NAME="${READ_NAME}"
#		echo "Sample: ${SAMPLE_NAME}"
#	else
#		echo "Sample: ${SAMPLE_NAME}"
#	fi

	###############################################################################
	echo ""
	echo ". Starting Deepvariant..."
	echo ""
	LC_ALL=C singularity run -B ${BIND_DIR}:${BIND_DIR} \
	${INSTALLATION_DIR}/4.snp_calling/deepvariant_1.5.0.sif /opt/deepvariant/bin/run_deepvariant \
	--model_type=WGS \
	--ref="${ASSEMBLY_NAME}.fa" \
	--reads="${OUT_DIR}/jATG/${SPECIES_NAME}/${ASSEMBLY_ID}/${SAMPLE_NAME}/4.calling/1_BAMs/${SAMPLE_NAME}.merged.bam" \
	--output_vcf="${SAMPLE_NAME}.vcf.gz" \
	--output_gvcf="${SAMPLE_NAME}.g.vcf.gz" \
	--intermediate_results_dir="${TMPDIR}/${SAMPLE_NAME}" \
	--num_shards=18

elif  [[ "${READ_TYPE}" == "HiFi" ]]
then

	# get READ/SAMPLE variables
#	if [ -z "${SAMPLE_NAME}" ]
#	then
#        	READ=$(ls ${TRIM_DIR}/*.trimmed.fq.gz | tail -n 1)
#        	READ_NAME=$(basename ${READ} .trimmed.fq.gz)
#	        SAMPLE_NAME="${READ_NAME}"
#	        echo "Sample: ${SAMPLE_NAME}"
#	else
#	        echo "Sample: ${SAMPLE_NAME}"
#	fi

	###############################################################################
	echo ""
	echo ". Starting Deepvariant..."
	echo ""
	LC_ALL=C singularity run -B ${BIND_DIR}:${BIND_DIR} \
	 ${INSTALLATION_DIR}/4.snp_calling/deepvariant_1.5.0.sif /opt/deepvariant/bin/run_deepvariant \
	--model_type=PACBIO \
	--ref="${ASSEMBLY_NAME}.fa" \
	--reads="${OUT_DIR}/jATG/${SPECIES_NAME}/${ASSEMBLY_ID}/${SAMPLE_NAME}/4.calling/1_BAMs/${SAMPLE_NAME}.merged.bam" \
	--output_vcf="${SAMPLE_NAME}.vcf.gz" \
	--output_gvcf="${SAMPLE_NAME}.g.vcf.gz" \
	--intermediate_results_dir="${TMPDIR}/${SAMPLE_NAME}" \
	--num_shards=18

else
        echo 'Invalid read type. Valid values for READ_TYPE variable in variables.cnf file are: "illuminaPE" or "HiFi"'
fi


###############################################################################
echo ""
echo ". Filtering VCF for PASS calls..."
echo ""

zgrep -v RefCall "${SAMPLE_NAME}.vcf.gz" | bgzip > "${SAMPLE_NAME}.PASS.vcf.gz"
bcftools index "${SAMPLE_NAME}.PASS.vcf.gz"


###############################################################################
echo ""
echo ". Creating basepair resolution gVCF..."
echo ""
bcftools convert --gvcf2vcf "${SAMPLE_NAME}.g.vcf.gz" --fasta-ref "${ASSEMBLY_NAME}.fa" | bgzip > "${SAMPLE_NAME}.FULL.g.vcf.gz"
bcftools index  "${SAMPLE_NAME}.FULL.g.vcf.gz"


# cleaning a little
rm "${ASSEMBLY_NAME}.fa" "${ASSEMBLY_NAME}.fa.fai"
