#!/bin/bash

#SBATCH -J Cleaning

#SBATCH --cpus-per-task=1
#SBATCH --mem=2G
#SBATCH --time=8:00:00


cd ${OUT_DIR}/jATG/${SPECIES_NAME}/${ASSEMBLY_ID}/${SAMPLE_NAME}/4.calling/2_VCFs

[[ -f filtered/${SAMPLE_NAME}.Genot.PASS.bcf && \
$(stat -c %s filtered/${SAMPLE_NAME}.Genot.PASS.bcf) -gt 1000000 ]] && \
rm -f *interval* temp* *full.vcf.gz ${OUT_DIR}/jATG/${SPECIES_NAME}/${ASSEMBLY_ID}/${SAMPLE_NAME}/4.calling/1_BAMs/temp_*
