#!/bin/bash

#SBATCH -J MergeVCF

#SBATCH --cpus-per-task=2
#SBATCH --mem=8G
#SBATCH --time=2-00:00:00

export PATH="${CONDA_BIN_DIR}:${PATH}"
source activate jATG_env

${SINGULARITY_LOAD}

TIMESTAMP=$(date +%F_%T)

cd ${OUT_DIR}/jATG/${SPECIES_NAME}/${ASSEMBLY_ID}/${SAMPLE_NAME}/4.calling/2_VCFs

export LC_ALL=C

###############################################################################
echo "${TIMESTAMP} Starting VCFs merging..."

GATHERVCFS="singularity exec -B ${BIND_DIR}:${BIND_DIR} ${INSTALLATION_DIR}/containers/gatk_latest.sif gatk --java-options -Xmx${SLURM_MEM_PER_NODE}M GatherVcfs"

# loop over files
for interval_vcf in *.Genot.interval*.vcf.gz
do
    # append each file to the command string
    GATHERVCFS+=" --INPUT $interval_vcf"
done

# add the output file to the command
GATHERVCFS+=" --OUTPUT ${SAMPLE_NAME}.Genot.full.vcf.gz --TMP_DIR ${TMPDIR}"

# run the command
$GATHERVCFS


###############################################################################
echo "${TIMESTAMP} Adding MASKED tag for repetitive content..."

awk '{print $1"\t"$2"\t"$3"\t1"}' ${MASKED_BED} > temp_masked.bed
echo '##INFO=<ID=MASKED,Number=0,Type=Flag,Description="Masked due to overlap with RepeatMasker BED file">' > temp_head.txt

bcftools annotate --threads 2 -a temp_masked.bed -c CHROM,FROM,TO,INFO/MASKED -h temp_head.txt ${SAMPLE_NAME}.Genot.full.vcf.gz -O b -o temp_${SAMPLE_NAME}.Genot.full.masked.bcf


###############################################################################
echo "${TIMESTAMP} Filling INFO/TYPE tag..."

bcftools +fill-tags --threads 2 temp_${SAMPLE_NAME}.Genot.full.masked.bcf -O b -o ${SAMPLE_NAME}.Genot.full.bcf -- -t TYPE


###############################################################################
echo "${TIMESTAMP} Indexing..."

bcftools index --threads 2 ${SAMPLE_NAME}.Genot.full.bcf


###############################################################################
echo "${TIMESTAMP} Getting some stats..."

bcftools stats --threads 2 -s - ${SAMPLE_NAME}.Genot.full.bcf > ${SAMPLE_NAME}.Genot.full.stats
