#!/bin/bash

#SBATCH -J Merge

#SBATCH --cpus-per-task=2
#SBATCH --mem=8G
#SBATCH --time=2-00:00:00

export PATH="${CONDA_BIN_DIR}:${PATH}"
source activate CALLING_env

cd ${OUT_DIR}/jATG/${SPECIES_NAME}/${ASSEMBLY_ID}/${SAMPLE_NAME}/4.calling/1_BAMs

###############################################################################
echo ""
echo ". Starting merging bams..."
echo ""
ls *.markdup.bam > bam_list

srun \
samtools merge -b bam_list -o "${SAMPLE_NAME}.merged.bam"


###############################################################################
echo ""
echo ". Indexing bam..."
echo ""
srun \
samtools index "${SAMPLE_NAME}.merged.bam"
