#!/bin/bash

#SBATCH -J MergeVCF

#SBATCH --cpus-per-task=2
#SBATCH --mem=8G
#SBATCH --time=2-00:00:00

export PATH="${CONDA_BIN_DIR}:${PATH}"
source activate jATG_env

${SINGULARITY_LOAD}

cd ${OUT_DIR}/jATG/${SPECIES_NAME}/${ASSEMBLY_ID}/${SAMPLE_NAME}/4.calling/2_VCFs

export LC_ALL=C



###############################################################################
echo "$(date +%F_%T) Adding MASKED tag for repetitive content..."

rm -r filtered/
rm temp*

mv ${SAMPLE_NAME}.Genot.full.bcf temp_Genot.full.bcf
mv ${SAMPLE_NAME}.Genot.full.bcf.csi temp_Genot.full.bcf.csi

awk '{print $1"\t"$2"\t"$3"\t1"}' ${MASKED_BED} > temp_masked.bed
echo '##INFO=<ID=MASKED,Number=0,Type=Flag,Description="Masked due to overlap with RepeatMasker BED file">' > temp_head.txt

bcftools annotate --threads 2 -a temp_masked.bed -c CHROM,FROM,TO,INFO/MASKED -h temp_head.txt temp_Genot.full.bcf -O b -o temp_${SAMPLE_NAME}.Genot.full.masked.bcf


###############################################################################
echo "$(date +%F_%T) Filling INFO/TYPE tag..."

bcftools +fill-tags --threads 2 temp_${SAMPLE_NAME}.Genot.full.masked.bcf -O b -o ${SAMPLE_NAME}.Genot.full.bcf -- -t TYPE


###############################################################################
echo "$(date +%F_%T) Indexing..."

bcftools index --threads 2 ${SAMPLE_NAME}.Genot.full.bcf


###############################################################################
echo "$(date +%F_%T) Getting some stats..."

bcftools stats --threads 2 -s - ${SAMPLE_NAME}.Genot.full.bcf > ${SAMPLE_NAME}.Genot.full.stats


echo "$(date +%F_%T) Ending job..."
